name: Deploy project
on: [push, workflow_dispatch]
jobs:
  linting-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: install nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependancies
        run: npm ci
      - name: Lint
        run: npm run lint
